CREATE TABLE `Dim_Realizacao` (
  `realizacao_id` int unsigned auto_increment,
  `ano_realizacao` year,
  PRIMARY KEY (`realizacao_id`)
);

CREATE TABLE `Dim_Instituicao` (
  `instituicao_id` int unsigned auto_increment,
  `codigo_emec` char(5),
  `categoria_administrativa` varchar(255),
  `organizacao_academica` varchar(255),
  PRIMARY KEY (`instituicao_id`)
);

CREATE TABLE `Dim_Curso` (
  `curso_id` int unsigned auto_increment,
  `codigo_enade` int(7),
  `grupo_area` varchar(255),
  `modalidade` varchar(255),
  `codigo_municipio` varchar(255),
  `codigo_uf` varchar(255),
  `codigo_regiao` varchar(255),
  PRIMARY KEY (`curso_id`)
);

CREATE TABLE `Dim_Estudante` (
  `estudante_id` int unsigned auto_increment,
  `idade` int(2),
  `sexo` varchar(100),
  `ano_fim_ensino_medio` varchar(100),
  `ano_inicio_graduacao` varchar(100),
  `turno_graduacao` varchar(100),
  `forma_inscricao` varchar(100),
  `tipo_inscricao` varchar(100),
  PRIMARY KEY (`estudante_id`)
);

CREATE TABLE `Dim_Tipo_Presenca` (
  `tipo_presenca_id` int unsigned auto_increment,
  `tipo_presenca` varchar(100),
  `tipo_presenca_prova` varchar(100),
  `tipo_presenca_geral_obj` varchar(100),
  `tipo_presenca_geral_discursiva` varchar(100),
  `tipo_presenca_especifico_obj` varchar(100),
  `tipo_presenca_especifico_discursiva` varchar(100),
  PRIMARY KEY (`tipo_presenca_id`)
);

CREATE TABLE `Dim_Situacao_Parte_Discursiva` (
  `situacao_parte_discursiva_id` int unsigned auto_increment,
  `situacao_geral_discursiva_q1` varchar(100),
  `situacao_geral_discursiva_q2` varchar(100),
  `situacao_especifico_discursiva_q1` varchar(100),
  `situacao_especifico_discursiva_q2` varchar(100),
  `situacao_especifico_discursiva_q3` varchar(100),
  PRIMARY KEY (`situacao_parte_discursiva_id`)
);

CREATE TABLE `Dim_Avaliacao_Gabarito` (
  `avaliacao_gabarito_id` int unsigned auto_increment,
  `total_itens_obj_geral` int(1),
  `total_itens_obj_geral_anulados` int(1),
  `total_itens_obj_geral_invalidos` int(1),
  `total_itens_obj_geral_nao_aplica` int(1),
  `total_itens_obj_especifico` int(2),
  `total_itens_obj_especifico_anulados` int(2),
  `total_itens_obj_especifico_invalidos` int(1),
  `total_itens_obj_especifico_nao_aplica` int(1),
  `gabarito_geral_original` char(8),
  `gabarito_geral_final` char(8),
  `gabarito_especifico_original` char(27),
  `gabarito_especifico_final` char(27),
  PRIMARY KEY (`avaliacao_gabarito_id`)
);

CREATE TABLE `Dim_Questionario_Pergunta` (
  `questionario_pergunta_id` int unsigned auto_increment,
  `questionario_prova_1` varchar(255),
  `questionario_prova_2` text(255),
  `questionario_prova_3` text(255),
  `questionario_prova_4` text(255),
  `questionario_prova_5` text(255),
  `questionario_prova_6` text(255),
  `questionario_prova_7` text(255),
  `questionario_prova_8` text(255),
  `questionario_prova_9` text(255),
  `questionario_estudante_01` text(255),
  `questionario_estudante_02` text(255),
  `questionario_estudante_03` text(255),
  `questionario_estudante_04` text(255),
  `questionario_estudante_05` text(255),
  `questionario_estudante_06` text(255),
  `questionario_estudante_07` text(255),
  `questionario_estudante_08` text(255),
  `questionario_estudante_09` text(255),
  `questionario_estudante_10` text(255),
  `questionario_estudante_11` text(255),
  `questionario_estudante_12` text(255),
  `questionario_estudante_13` text(255),
  `questionario_estudante_14` text(255),
  `questionario_estudante_15` text(255),
  `questionario_estudante_16` text(255),
  `questionario_estudante_17` text(255),
  `questionario_estudante_18` text(255),
  `questionario_estudante_19` text(255),
  `questionario_estudante_20` text(255),
  `questionario_estudante_21` text(255),
  `questionario_estudante_22` text(255),
  `questionario_estudante_23` text(255),
  `questionario_estudante_24` text(255),
  `questionario_estudante_25` text(255),
  `questionario_estudante_26` text(255),
  `questionario_estudante_27` text(255),
  `questionario_estudante_28` text(255),
  `questionario_estudante_29` text(255),
  `questionario_estudante_30` text(255),
  `questionario_estudante_31` text(255),
  `questionario_estudante_32` text(255),
  `questionario_estudante_33` text(255),
  `questionario_estudante_34` text(255),
  `questionario_estudante_35` text(255),
  `questionario_estudante_36` text(255),
  `questionario_estudante_37` text(255),
  `questionario_estudante_38` text(255),
  `questionario_estudante_39` text(255),
  `questionario_estudante_40` text(255),
  `questionario_estudante_41` text(255),
  `questionario_estudante_42` text(255),
  `questionario_estudante_43` text(255),
  `questionario_estudante_44` text(255),
  `questionario_estudante_45` text(255),
  `questionario_estudante_46` text(255),
  `questionario_estudante_47` text(255),
  `questionario_estudante_48` text(255),
  `questionario_estudante_49` text(255),
  `questionario_estudante_50` text(255),
  `questionario_estudante_51` text(255),
  `questionario_estudante_52` text(255),
  `questionario_estudante_53` text(255),
  `questionario_estudante_54` text(255),
  `questionario_estudante_55` text(255),
  `questionario_estudante_56` text(255),
  `questionario_estudante_57` text(255),
  `questionario_estudante_58` text(255),
  `questionario_estudante_59` text(255),
  `questionario_estudante_60` text(255),
  `questionario_estudante_61` text(255),
  `questionario_estudante_62` text(255),
  `questionario_estudante_63` text(255),
  `questionario_estudante_64` text(255),
  `questionario_estudante_65` text(255),
  `questionario_estudante_66` text(255),
  `questionario_estudante_67` text(255),
  `questionario_estudante_68` text(255),
  `questionario_estudante_69` text(255),
  `questionario_estudante_70` text(255),
  `questionario_estudante_71` text(255),
  `questionario_estudante_72` text(255),
  `questionario_estudante_73` text(255),
  `questionario_estudante_74` text(255),
  `questionario_estudante_75` text(255),
  `questionario_estudante_76` text(255),
  `questionario_estudante_77` text(255),
  `questionario_estudante_78` text(255),
  `questionario_estudante_79` text(255),
  `questionario_estudante_80` text(255),
  `questionario_estudante_81` text(255),
  PRIMARY KEY (`questionario_pergunta_id`)
);

CREATE TABLE `Dim_Questionario_Resposta` (
  `questionario_resposta_id` int unsigned auto_increment,
  `questionario_prova_1` text(255),
  `questionario_prova_2` text(255),
  `questionario_prova_3` text(255),
  `questionario_prova_4` text(255),
  `questionario_prova_5` text(255),
  `questionario_prova_6` text(255),
  `questionario_prova_7` text(255),
  `questionario_prova_8` text(255),
  `questionario_prova_9` text(255),
  `questionario_estudante_01` text(255),
  `questionario_estudante_02` text(255),
  `questionario_estudante_03` text(255),
  `questionario_estudante_04` text(255),
  `questionario_estudante_05` text(255),
  `questionario_estudante_06` text(255),
  `questionario_estudante_07` text(255),
  `questionario_estudante_08` text(255),
  `questionario_estudante_09` text(255),
  `questionario_estudante_10` text(255),
  `questionario_estudante_11` text(255),
  `questionario_estudante_12` text(255),
  `questionario_estudante_13` text(255),
  `questionario_estudante_14` text(255),
  `questionario_estudante_15` text(255),
  `questionario_estudante_16` text(255),
  `questionario_estudante_17` text(255),
  `questionario_estudante_18` text(255),
  `questionario_estudante_19` text(255),
  `questionario_estudante_20` text(255),
  `questionario_estudante_21` text(255),
  `questionario_estudante_22` text(255),
  `questionario_estudante_23` text(255),
  `questionario_estudante_24` text(255),
  `questionario_estudante_25` text(255),
  `questionario_estudante_26` text(255),
  `questionario_estudante_27` text(255),
  `questionario_estudante_28` text(255),
  `questionario_estudante_29` text(255),
  `questionario_estudante_30` text(255),
  `questionario_estudante_31` text(255),
  `questionario_estudante_32` text(255),
  `questionario_estudante_33` text(255),
  `questionario_estudante_34` text(255),
  `questionario_estudante_35` text(255),
  `questionario_estudante_36` text(255),
  `questionario_estudante_37` text(255),
  `questionario_estudante_38` text(255),
  `questionario_estudante_39` text(255),
  `questionario_estudante_40` text(255),
  `questionario_estudante_41` text(255),
  `questionario_estudante_42` text(255),
  `questionario_estudante_43` text(255),
  `questionario_estudante_44` text(255),
  `questionario_estudante_45` text(255),
  `questionario_estudante_46` text(255),
  `questionario_estudante_47` text(255),
  `questionario_estudante_48` text(255),
  `questionario_estudante_49` text(255),
  `questionario_estudante_50` text(255),
  `questionario_estudante_51` text(255),
  `questionario_estudante_52` text(255),
  `questionario_estudante_53` text(255),
  `questionario_estudante_54` text(255),
  `questionario_estudante_55` text(255),
  `questionario_estudante_56` text(255),
  `questionario_estudante_57` text(255),
  `questionario_estudante_58` text(255),
  `questionario_estudante_59` text(255),
  `questionario_estudante_60` text(255),
  `questionario_estudante_61` text(255),
  `questionario_estudante_62` text(255),
  `questionario_estudante_63` text(255),
  `questionario_estudante_64` text(255),
  `questionario_estudante_65` text(255),
  `questionario_estudante_66` text(255),
  `questionario_estudante_67` text(255),
  `questionario_estudante_68` text(255),
  `questionario_estudante_69` text(255),
  `questionario_estudante_70` text(255),
  `questionario_estudante_71` text(255),
  `questionario_estudante_72` text(255),
  `questionario_estudante_73` text(255),
  `questionario_estudante_74` text(255),
  `questionario_estudante_75` text(255),
  `questionario_estudante_76` text(255),
  `questionario_estudante_77` text(255),
  `questionario_estudante_78` text(255),
  `questionario_estudante_79` text(255),
  `questionario_estudante_80` text(255),
  `questionario_estudante_81` text(255),
  PRIMARY KEY (`questionario_resposta_id`)
);

CREATE TABLE `Fato_Avaliacao` (
  `realizacao_id` int unsigned,
  `estudante_id` int unsigned,
  `curso_id` int unsigned,
  `instituicao_id` int unsigned,
  `tipo_presenca_id` int unsigned,
  `situacao_parte_discursiva_id` int unsigned,
  `avaliacao_gabarito_id` int unsigned,
  `questionario_pergunta_id` int unsigned,
  `questionario_resposta_id` int unsigned,
  `escolhas_geral_obj` varchar(50),
  `acertos_geral_obj` varchar(50),
  `escolhas_especifico_obj` char(50),
  `acertos_especifico_obj` char(50),
  `nota` varchar(50),
  `nota_geral` varchar(50),
  `nota_geral_obj` varchar(50),
  `nota_geral_discursiva` varchar(50),
  `nota_geral_discursiva_q1` varchar(50),
  `nota_geral_discursiva_q1_portugues` varchar(50),
  `nota_geral_discursiva_q1_conteudo`varchar(50),
  `nota_geral_discursiva_q2` varchar(50),
  `nota_geral_discursiva_q2_portugues` varchar(50),
  `nota_geral_discursiva_q2_conteudo` varchar(50),
  `nota_especifico` varchar(50),
  `nota_especifico_obj` varchar(50),
  `nota_especifico_discursiva` varchar(50),
  `nota_especifico_discursiva_q1` varchar(50),
  `nota_especifico_discursiva_q2` varchar(50),
  `nota_especifico_discursiva_q3` varchar(50),
  PRIMARY KEY (`realizacao_id`, `estudante_id`, `curso_id`, `instituicao_id`, `tipo_presenca_id`, `situacao_parte_discursiva_id`, `avaliacao_gabarito_id`, `questionario_pergunta_id`, `questionario_resposta_id`),
  FOREIGN KEY (`realizacao_id`) REFERENCES `Dim_Realizacao`(`realizacao_id`),
  FOREIGN KEY (`estudante_id`) REFERENCES `Dim_Estudante`(`estudante_id`),
  FOREIGN KEY (`curso_id`) REFERENCES `Dim_Curso`(`curso_id`),
  FOREIGN KEY (`instituicao_id`) REFERENCES `Dim_Instituicao`(`instituicao_id`),
  FOREIGN KEY (`tipo_presenca_id`) REFERENCES `Dim_Tipo_Presenca`(`tipo_presenca_id`),
  FOREIGN KEY (`situacao_parte_discursiva_id`) REFERENCES `Dim_Situacao_Parte_Discursiva`(`situacao_parte_discursiva_id`),
  FOREIGN KEY (`avaliacao_gabarito_id`) REFERENCES `Dim_Avaliacao_Gabarito`(`avaliacao_gabarito_id`),
  FOREIGN KEY (`questionario_resposta_id`) REFERENCES `Dim_Questionario_Resposta`(`questionario_resposta_id`)
);




